## Partie 1 – Series

Une **Series** est la structure de base de pandas : une colonne de données
à une seule dimension. Chaque valeur possède une étiquette appelée **index**.
On peut la voir comme une seule colonne d'un tableur, où l'index joue le rôle
des numéros de ligne.

### 1. Créer une Series contenant 4 températures

- **Objectif** : créer une Series à partir d'une liste de valeurs.
- **Syntaxe** : `pd.Series([valeur1, valeur2, ...])`

In [3]:
import pandas as pd

temperatures = pd.Series([22.5, 24.1, 19.8, 26.3])
temperatures

0    22.5
1    24.1
2    19.8
3    26.3
dtype: float64

### 2. Afficher l'index de la Series

- **Objectif** : voir les étiquettes attribuées à chaque valeur.
- **Syntaxe** : `ma_series.index`

In [6]:
temperatures.index

RangeIndex(start=0, stop=4, step=1)

### 3 & 4. Afficher la première et la dernière valeur

- **Objectif** : accéder à une valeur par sa **position**.
- **Syntaxe** : `ma_series.iloc[position]`
  - `iloc` = *integer location* = accès par position (0 = première).
  - La position `-1` désigne toujours le **dernier** élément.

In [7]:
print("Première valeur :", temperatures.iloc[0])
print("Dernière valeur :", temperatures.iloc[-1])

Première valeur : 22.5
Dernière valeur : 26.3

### 5. Créer une Series de températures indexée par les heures (12h à 15h)

Deux méthodes possibles :
- **Objectif** : associer à chaque température une étiquette (l'heure de mesure).
- **Syntaxe 1** (paramètre `index`) : `pd.Series(valeurs, index=liste_etiquettes)`
- **Syntaxe 2** (dictionnaire) : `pd.Series({etiquette: valeur, ...})`
  → les **clés** du dictionnaire deviennent automatiquement l'index.

In [8]:
# Façon 1 : avec le paramètre index
temp_heures_1 = pd.Series([22.5, 24.1, 19.8, 26.3], index=["12h", "13h", "14h", "15h"])
print("Façon 1 :")
print(temp_heures_1)

# Façon 2 : à partir d'un dictionnaire
temp_heures_2 = pd.Series({"12h": 22.5, "13h": 24.1, "14h": 19.8, "15h": 26.3})
print("\nFaçon 2 :")
print(temp_heures_2)

Façon 1 :
12h    22.5
13h    24.1
14h    19.8
15h    26.3
dtype: float64

Façon 2 :
12h    22.5
13h    24.1
14h    19.8
15h    26.3
dtype: float64

### 6. Afficher la première et la dernière valeur

- **Objectif** : réutiliser l'accès par position sur la Series indexée par heures.
- **Syntaxe** : `ma_series.iloc[0]` et `ma_series.iloc[-1]`
  (On pourrait aussi passer par l'étiquette : `ma_series["12h"]`, `ma_series["15h"]`.)

In [9]:
print("Première valeur :", temp_heures_1.iloc[0])
print("Dernière valeur :", temp_heures_1.iloc[-1])

Première valeur : 22.5
Dernière valeur : 26.3

## Partie 2 – DataFrame

Un **DataFrame** est un tableau à deux dimensions : plusieurs colonnes nommées
et des lignes indexées. C'est la structure centrale de pandas, équivalente à
une feuille de calcul.

### 1. Créer et afficher le DataFrame df_test

- **Objectif** : construire un DataFrame à partir d'un dictionnaire.
- **Syntaxe** : `pd.DataFrame(dictionnaire)`
  → chaque **clé** du dictionnaire devient un **nom de colonne**,
    et la **liste** associée devient le **contenu** de la colonne.

In [10]:
data = {
    "capteur": ["C001", "C002", "C003"],
    "temperature": [24.5, 25.1, 26.3],
    "humidite": [65, 67, 70]
}

df_test = pd.DataFrame(data)
df_test

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

### 2. Importer le dataset mesures_capteurs.csv dans le DataFrame df

- **Objectif** : charger un fichier CSV pour le transformer en DataFrame.
- **Syntaxe** : `pd.read_csv("chemin/vers/le/fichier.csv")`
  → `read_csv` lit un fichier de valeurs séparées par des virgules
    (CSV = *Comma-Separated Values*) et le convertit en DataFrame.

In [11]:
df = pd.read_csv("../data/mesures_capteurs.csv")
df

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
...,...,...,...,...,...,...,...,...,...
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

### 3. Afficher les dimensions de df

- **Objectif** : connaître le nombre de lignes et de colonnes.
- **Syntaxe** : `df.shape`
  → renvoie un couple `(nombre_de_lignes, nombre_de_colonnes)`.

In [12]:
df.shape

(605, 9)

## Partie 3 – Exploration

Avant d'analyser un jeu de données, on l'explore pour comprendre sa taille,
ses colonnes et le type de chaque information. C'est le premier réflexe de
tout data scientist face à un nouveau fichier.

### 1 & 2. Afficher les premières lignes

- **Objectif** : jeter un œil au début du tableau.
- **Syntaxe** : `df.head()` affiche les 5 premières lignes par défaut ;
  `df.head(n)` en affiche `n`.

In [13]:
print("5 premières lignes :")
display(df.head())

print("10 premières lignes :")
display(df.head(10))

5 premières lignes :

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

10 premières lignes :

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
5,M0595,2026-01-29 18:00:00,C007,B003,24.51,58.01,1013.34,146.10,OK
6,M0011,2026-01-05 10:00:00,C011,B004,29.23,70.43,1007.68,290.45,OK
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
8,M0444,2026-01-23 11:00:00,C012,B004,23.11,82.06,1021.96,293.36,OK
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK

### 3. Afficher les dernières lignes

- **Objectif** : regarder la fin du tableau.
- **Syntaxe** : `df.tail()` affiche les 5 dernières lignes (`tail` = « queue »).

### 4 & 5. Afficher le nombre de lignes et de colonnes

- **Objectif** : récupérer séparément le nombre de lignes puis de colonnes.
- **Syntaxe** : `df.shape` renvoie `(lignes, colonnes)`.
  On accède à chaque valeur par sa position : `df.shape[0]` (lignes),
  `df.shape[1]` (colonnes).

In [14]:
print("Nombre de lignes :", df.shape[0])
print("Nombre de colonnes :", df.shape[1])

Nombre de lignes : 605
Nombre de colonnes : 9

### 6. Afficher les noms des colonnes

- **Objectif** : lister les intitulés de colonnes.
- **Syntaxe** : `df.columns`

In [15]:
df.columns

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite', 'pression', 'consommation', 'etat'],
      dtype='str')

### 7. Afficher les informations générales

- **Objectif** : obtenir un résumé technique du tableau : nombre de lignes,
  nom et type de chaque colonne, et nombre de valeurs non-manquantes.
- **Syntaxe** : `df.info()`

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    str
 1   date_heure    605 non-null    str
 2   id_capteur    605 non-null    str
 3   batiment      605 non-null    str
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    str
dtypes: float64(4), str(5)
memory usage: 42.7 KB

### 8. Afficher les statistiques descriptives

- **Objectif** : obtenir d'un coup les statistiques des colonnes numériques
  (moyenne, min, max, écart-type, quartiles).
- **Syntaxe** : `df.describe()`

In [17]:
df.describe()

       temperature   humidite     pression  consommation
count   599.000000  600.00000   600.000000    600.000000
mean     24.878314   64.92620  1012.221900    208.675417
std       4.059576   10.76905    10.599042     72.243567
min     -18.500000   28.52000   850.000000     18.120000
25%      22.570000   58.17250  1006.790000    160.177500
50%      24.860000   65.37500  1012.855000    206.150000
75%      27.275000   71.61500  1017.827500    254.127500
max      58.700000  145.00000  1038.430000    875.000000

## Partie 4 – Sélection

Sélectionner, c'est extraire une partie du tableau : une colonne, plusieurs
colonnes, ou un sous-ensemble de lignes. Deux outils clés : `loc` (par étiquette)
et `iloc` (par position).

### 1. Sélectionner la colonne "temperature"
- **Objectif** : extraire une seule colonne (renvoie une Series).
- **Syntaxe** : `df["nom_colonne"]`

In [18]:
df["temperature"]

0      25.46
1      24.00
2      25.82
3      28.23
4      20.58
       ...
600    23.67
601    24.34
602    23.73
603    24.83
604    17.02
Name: temperature, Length: 605, dtype: float64

### 2. Sélectionner plusieurs colonnes
- **Objectif** : extraire plusieurs colonnes (renvoie un DataFrame).
- **Syntaxe** : `df[["col1", "col2", ...]]` → noter les **doubles crochets**.

In [19]:
df[["temperature", "humidite", "pression", "consommation"]]

     temperature  humidite  pression  consommation
0          25.46     58.06   1008.95        287.28
1          24.00     79.73    993.39        116.20
2          25.82     54.47   1010.32        288.50
3          28.23     69.39   1019.62        136.65
4          20.58     53.80   1016.58        182.62
..           ...       ...       ...           ...
600        23.67     60.28   1015.11        282.36
601        24.34     61.42   1019.43        357.43
602        23.73     63.49   1016.46        152.79
603        24.83     79.77   1017.05        170.97
604        17.02     52.04   1001.14         44.99

[605 rows x 4 columns]

### 3. Les 5 premières lignes avec loc
- **Objectif** : sélectionner des lignes par leur étiquette d'index.
- **Syntaxe** : `df.loc[debut:fin]` → avec `loc`, la borne de fin est **incluse**.

In [20]:
df.loc[0:4]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

### 4. Les 5 premières lignes et 4 premières colonnes avec iloc
- **Objectif** : sélectionner par **position** (numéros), lignes ET colonnes.
- **Syntaxe** : `df.iloc[lignes, colonnes]` → avec `iloc`, la borne de fin est **exclue**.

In [21]:
df.iloc[0:5, 0:4]

  id_mesure           date_heure id_capteur batiment
0     M0413  2026-01-22 04:00:00       C005     B002
1     M0290  2026-01-17 01:00:00       C002     B001
2     M0077  2026-01-08 04:00:00       C005     B002
3     M0079  2026-01-08 06:00:00       C007     B003
4     M0183  2026-01-12 14:00:00       C003     B001

## Partie 5 – Manipulation des colonnes

On peut créer de nouvelles colonnes, les catégoriser, les renommer ou les
supprimer. Ces opérations préparent les données pour l'analyse.

### 1. Ajouter la colonne "temperature_fahrenheit"
- **Objectif** : créer une colonne calculée à partir d'une autre.
- **Syntaxe** : `df["nouvelle"] = <calcul sur une colonne existante>`
- **Formule** : °F = °C × 9/5 + 32

In [22]:
df["temperature_fahrenheit"] = df["temperature"] * 9/5 + 32
df[["temperature", "temperature_fahrenheit"]].head()

   temperature  temperature_fahrenheit
0        25.46                  77.828
1        24.00                  75.200
2        25.82                  78.476
3        28.23                  82.814
4        20.58                  69.044

### 2. Ajouter la colonne "niveau_temperature"
- **Objectif** : catégoriser chaque ligne selon une condition.
- **Syntaxe** : `np.where(condition, valeur_si_vrai, valeur_si_faux)`
  → il faut importer numpy : `import numpy as np`.

In [23]:
import numpy as np

df["niveau_temperature"] = np.where(df["temperature"] > 30, "Élevée", "Normale")
df["niveau_temperature"].value_counts()

niveau_temperature
Normale    559
Élevée      46
Name: count, dtype: int64

### 3. Renommer "humidite" en "humidite_relative"
- **Objectif** : changer le nom d'une colonne.
- **Syntaxe** : `df.rename(columns={"ancien": "nouveau"})`
  → on réassigne le résultat à `df` pour que le changement soit conservé.

In [24]:
df = df.rename(columns={"humidite": "humidite_relative"})
df.columns

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite_relative', 'pression', 'consommation', 'etat',
       'temperature_fahrenheit', 'niveau_temperature'],
      dtype='str')

### 4. Supprimer la colonne "temperature_fahrenheit"
- **Objectif** : retirer une colonne devenue inutile.
- **Syntaxe** : `df.drop(columns=["nom_colonne"])`

In [25]:
df = df.drop(columns=["temperature_fahrenheit"])
df.columns

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite_relative', 'pression', 'consommation', 'etat',
       'niveau_temperature'],
      dtype='str')

## Partie 6 – Filtrage

Le filtrage garde uniquement les lignes qui respectent une condition. On écrit
une condition entre crochets ; pour combiner deux conditions, on utilise
`&` (ET) et `|` (OU), chaque condition entre parenthèses.

### 1. Lignes où température > 30
- **Objectif** : filtrer selon une seule condition.
- **Syntaxe** : `df[df["colonne"] > valeur]`

In [26]:
df[df["temperature"] > 30]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK,Élevée
43,M0575,2026-01-28 22:00:00,C011,B004,34.72,57.50,1008.94,266.22,ALERTE,Élevée
47,M0082,2026-01-08 09:00:00,C010,B004,32.46,72.31,1000.42,276.99,ALERTE,Élevée
63,M0064,2026-01-07 15:00:00,C004,B002,31.19,55.13,1011.04,264.98,OK,Élevée
79,M0275,2026-01-16 10:00:00,C011,B004,31.74,69.95,1020.79,335.89,OK,Élevée
88,M0288,2026-01-16 23:00:00,C012,B004,30.06,75.30,1014.47,323.32,OK,Élevée
103,M0311,2026-01-17 22:00:00,C011,B004,30.83,54.99,1026.47,256.11,OK,Élevée
112,M0149,2026-01-11 04:00:00,C005,B002,31.46,48.48,1002.75,210.94,OK,Élevée
118,M0365,2026-01-20 04:00:00,C005,B002,32.90,65.91,1027.28,246.08,ALERTE,Élevée
129,M0592,2026-01-29 15:00:00,C004,B002,33.60,79.80,1021.96,212.55,ALERTE,Élevée
137,M0076,2026-01-08 03:00:00,C004,B002,31.18,49.66,1019.91,215.22,OK,Élevée
145,M0503,2026-01-25 22:00:00,C011,B004,30.57,71.26,1002.88,359.97,OK,Élevée
146,M0118,2026-01-09 21:00:00,C010,B004,30.32,NaN,1015.78,261.68,OK,Élevée
165,M0323,2026-01-18 10:00:00,C011,B004,33.01,73.24,1014.36,260.24,ALERTE,Élevée
168,M0276,2026-01-16 11:00:00,C012,B004,30.39,71.14,1017.79,303.38,OK,Élevée
169,M0546,2026-01-27 17:00:00,C006,B002,32.36,67.34,998.10,184.89,ALERTE,Élevée
174,M0405,2026-01-21 20:00:00,C009,B003,31.74,47.23,1015.59,115.79,OK,Élevée
210,M0588,2026-01-29 11:00:00,C012,B004,31.51,72.49,1018.21,307.97,OK,Élevée
211,M0370,2026-01-20 09:00:00,C010,B004,33.29,50.43,1009.87,356.76,ALERTE,Élevée
224,M0303,2026-01-17 14:00:00,C003,B001,30.84,67.98,1020.09,157.99,OK,Élevée
243,M0416,2026-01-22 07:00:00,C008,B003,30.16,54.00,1012.18,875.00,ERREUR,Élevée
246,M0312,2026-01-17 23:00:00,C012,B004,30.13,65.68,1009.70,198.65,OK,Élevée
251,M0114,2026-01-09 17:00:00,C006,B002,31.85,85.77,1013.56,237.21,ALERTE,Élevée
257,M0378,2026-01-20 17:00:00,C006,B002,31.99,66.32,1013.54,254.67,OK,Élevée
264,M0191,2026-01-12 22:00:00,C011,B004,30.75,71.35,1018.92,308.66,OK,Élevée
274,M0046,2026-01-06 21:00:00,C010,B004,30.92,67.19,1009.71,329.78,OK,Élevée
280,M0585,2026-01-29 08:00:00,C009,B003,31.30,73.35,1021.40,187.98,OK,Élevée
322,M0120,2026-01-09 23:00:00,C012,B004,30.19,53.58,1013.05,396.90,ALERTE,Élevée
356,M0574,2026-01-28 21:00:00,C010,B004,30.61,60.73,1022.32,321.75,OK,Élevée
362,M0396,2026-01-21 11:00:00,C012,B004,30.57,63.47,1017.40,248.36,OK,Élevée
385,M0126,2026-01-10 05:00:00,C006,B002,30.09,73.95,1007.24,162.39,OK,Élevée
398,M0514,2026-01-26 09:00:00,C010,B004,30.48,93.57,1015.93,306.24,ALERTE,Élevée
401,M0586,2026-01-29 09:00:00,C010,B004,31.44,63.10,996.56,271.51,OK,Élevée
404,M0598,2026-01-29 21:00:00,C010,B004,30.37,64.55,997.31,311.77,OK,Élevée
417,M0432,2026-01-22 23:00:00,C012,B004,30.38,65.98,1005.48,256.18,OK,Élevée
437,M0286,2026-01-16 21:00:00,C010,B004,32.16,41.80,996.99,255.56,ALERTE,Élevée
438,M0558,2026-01-28 05:00:00,C006,B002,32.56,67.77,1016.88,181.51,ALERTE,Élevée
447,M0170,2026-01-12 01:00:00,C002,B001,31.15,69.20,1016.10,172.49,OK,Élevée
488,M0431,2026-01-22 22:00:00,C011,B004,30.14,51.02,1007.70,366.53,ALERTE,Élevée
492,M0552,2026-01-27 23:00:00,C012,B004,30.24,62.06,1009.35,299.69,OK,Élevée
500,M0062,2026-01-07 13:00:00,C002,B001,30.39,52.13,1004.23,262.66,OK,Élevée
502,M0048,2026-01-06 23:00:00,C012,B004,58.70,81.51,1026.79,271.92,ERREUR,Élevée
505,M0268,2026-01-16 03:00:00,C004,B002,30.34,64.23,1011.42,179.84,OK,Élevée
520,M0063,2026-01-07 14:00:00,C003,B001,32.72,53.28,1010.05,195.37,ALERTE,Élevée
541,M0202,2026-01-13 09:00:00,C010,B004,30.86,76.00,1011.94,224.01,OK,Élevée
558,M0346,2026-01-19 09:00:00,C010,B004,30.68,36.33,1010.46,272.59,OK,Élevée

### 2. Lignes où température > 30 ET humidité > 70
- **Objectif** : combiner deux conditions.
- **Syntaxe** : `df[(condition1) & (condition2)]`

In [27]:
df[(df["temperature"] > 30) & (df["humidite_relative"] > 70)]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
47,M0082,2026-01-08 09:00:00,C010,B004,32.46,72.31,1000.42,276.99,ALERTE,Élevée
88,M0288,2026-01-16 23:00:00,C012,B004,30.06,75.30,1014.47,323.32,OK,Élevée
129,M0592,2026-01-29 15:00:00,C004,B002,33.60,79.80,1021.96,212.55,ALERTE,Élevée
145,M0503,2026-01-25 22:00:00,C011,B004,30.57,71.26,1002.88,359.97,OK,Élevée
165,M0323,2026-01-18 10:00:00,C011,B004,33.01,73.24,1014.36,260.24,ALERTE,Élevée
168,M0276,2026-01-16 11:00:00,C012,B004,30.39,71.14,1017.79,303.38,OK,Élevée
210,M0588,2026-01-29 11:00:00,C012,B004,31.51,72.49,1018.21,307.97,OK,Élevée
251,M0114,2026-01-09 17:00:00,C006,B002,31.85,85.77,1013.56,237.21,ALERTE,Élevée
264,M0191,2026-01-12 22:00:00,C011,B004,30.75,71.35,1018.92,308.66,OK,Élevée
280,M0585,2026-01-29 08:00:00,C009,B003,31.30,73.35,1021.40,187.98,OK,Élevée
385,M0126,2026-01-10 05:00:00,C006,B002,30.09,73.95,1007.24,162.39,OK,Élevée
398,M0514,2026-01-26 09:00:00,C010,B004,30.48,93.57,1015.93,306.24,ALERTE,Élevée
502,M0048,2026-01-06 23:00:00,C012,B004,58.70,81.51,1026.79,271.92,ERREUR,Élevée
541,M0202,2026-01-13 09:00:00,C010,B004,30.86,76.00,1011.94,224.01,OK,Élevée

## Partie 7 – Tri

Trier réorganise les lignes selon les valeurs d'une ou plusieurs colonnes,
en ordre croissant ou décroissant.

### 1 à 3. Trier par température
- **Objectif** : ordonner les lignes selon la température.
- **Syntaxe** : `df.sort_values(by="colonne", ascending=True/False)`
  (`ascending=True` = croissant, valeur par défaut ; `False` = décroissant.)

In [28]:
df_trie1 = df.sort_values(by="temperature")                     # croissant
df_trie2 = df.sort_values(by="temperature", ascending=False)    # décroissant
top10 = df.sort_values(by="temperature", ascending=False).head(10)  # 10 plus élevées
top10

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
502,M0048,2026-01-06 23:00:00,C012,B004,58.70,81.51,1026.79,271.92,ERREUR,Élevée
43,M0575,2026-01-28 22:00:00,C011,B004,34.72,57.50,1008.94,266.22,ALERTE,Élevée
129,M0592,2026-01-29 15:00:00,C004,B002,33.60,79.80,1021.96,212.55,ALERTE,Élevée
211,M0370,2026-01-20 09:00:00,C010,B004,33.29,50.43,1009.87,356.76,ALERTE,Élevée
165,M0323,2026-01-18 10:00:00,C011,B004,33.01,73.24,1014.36,260.24,ALERTE,Élevée
118,M0365,2026-01-20 04:00:00,C005,B002,32.90,65.91,1027.28,246.08,ALERTE,Élevée
520,M0063,2026-01-07 14:00:00,C003,B001,32.72,53.28,1010.05,195.37,ALERTE,Élevée
438,M0558,2026-01-28 05:00:00,C006,B002,32.56,67.77,1016.88,181.51,ALERTE,Élevée
47,M0082,2026-01-08 09:00:00,C010,B004,32.46,72.31,1000.42,276.99,ALERTE,Élevée
169,M0546,2026-01-27 17:00:00,C006,B002,32.36,67.34,998.10,184.89,ALERTE,Élevée

### 4. Trier par bâtiment (croissant) puis température (décroissant)
- **Objectif** : trier sur plusieurs colonnes avec des ordres différents.
- **Syntaxe** : `df.sort_values(by=["col1","col2"], ascending=[True, False])`

In [29]:
df.sort_values(by=["batiment", "temperature"], ascending=[True, False])

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
520,M0063,2026-01-07 14:00:00,C003,B001,32.72,53.28,1010.05,195.37,ALERTE,Élevée
447,M0170,2026-01-12 01:00:00,C002,B001,31.15,69.20,1016.10,172.49,OK,Élevée
224,M0303,2026-01-17 14:00:00,C003,B001,30.84,67.98,1020.09,157.99,OK,Élevée
500,M0062,2026-01-07 13:00:00,C002,B001,30.39,52.13,1004.23,262.66,OK,Élevée
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK,Normale
...,...,...,...,...,...,...,...,...,...,...
277,M0383,2026-01-20 22:00:00,C011,B004,20.60,71.17,1017.44,293.92,OK,Normale
338,M0060,2026-01-07 11:00:00,C012,B004,20.56,63.37,1004.50,256.18,OK,Normale
487,M0538,2026-01-27 09:00:00,C010,B004,-18.50,66.27,1012.49,312.92,ERREUR,Normale
215,M0204,2026-01-13 11:00:00,C012,B004,NaN,59.96,1007.98,294.02,OK,Normale
513,M0490,2026-01-25 09:00:00,C010,B004,NaN,52.97,1010.71,253.63,OK,Normale

## Partie 8 – Analyse

On regroupe les données par catégorie (ici, par bâtiment) pour calculer des
statistiques par groupe. L'outil central est `groupby`.

In [30]:
df.groupby("batiment")["consommation"].mean()

batiment
B001    177.870927
B002    221.785333
B003    153.191000
B004    282.552282
Name: consommation, dtype: float64

### 2. Min, max, moyenne, écart-type de la température par bâtiment
- **Objectif** : plusieurs stats d'un coup sur une colonne groupée.
- **Syntaxe** : `df.groupby("cat")["col"].agg(["min","max","mean","std"])`

In [31]:
df.groupby("batiment")["temperature"].agg(["min", "max", "mean", "std"])

            min    max       mean       std
batiment
B001      16.77  32.72  23.578824  2.961211
B002      17.67  33.60  25.778000  2.951828
B003      14.11  31.74  23.013699  2.983902
B004     -18.50  58.70  27.119000  5.367361

### 3. Max et moyenne de température ET consommation, par bâtiment
- **Objectif** : stats différentes sur plusieurs colonnes.
- **Syntaxe** : `df.groupby("cat").agg({"col1": [...], "col2": [...]})`

In [32]:
df.groupby("batiment").agg({
    "temperature": ["max", "mean"],
    "consommation": ["max", "mean"]
})

         temperature            consommation
                 max       mean          max        mean
batiment
B001           32.72  23.578824       294.72  177.870927
B002           33.60  25.778000       335.20  221.785333
B003           31.74  23.013699       875.00  153.191000
B004           58.70  27.119000       411.12  282.552282

### 4 à 6. Statistiques globales
- **Objectif** : quelques agrégats sur l'ensemble du tableau.
- **Syntaxe** : `df["col"].mean()`, `.max()`, `.sum()`

In [33]:
print("Température moyenne globale :", df["temperature"].mean())
print("Température maximale :", df["temperature"].max())
print("Consommation totale :", df["consommation"].sum())

Température moyenne globale : 24.87831385642738
Température maximale : 58.7
Consommation totale : 125205.25

### 7. Quel bâtiment consomme le plus en moyenne ?
- **Objectif** : trouver la catégorie ayant la plus grande valeur.
- **Syntaxe** : `.idxmax()` renvoie l'étiquette du maximum.

In [34]:
conso_moyenne = df.groupby("batiment")["consommation"].mean()
print("Bâtiment le plus consommateur :", conso_moyenne.idxmax())

Bâtiment le plus consommateur : B004

### 8. Nombre d'alertes par bâtiment
- **Objectif** : compter les lignes en état "ALERTE" pour chaque bâtiment.
- **Syntaxe** : on filtre d'abord (`etat == "ALERTE"`), puis on groupe et on compte
  avec `.size()`

In [35]:
df[df["etat"] == "ALERTE"].groupby("batiment").size()

batiment
B001     2
B002     7
B003     5
B004    15
dtype: int64

## Partie 9 – Gestion des valeurs manquantes

Les valeurs manquantes (NaN) faussent les analyses. On les repère puis on les
remplace par une valeur raisonnable (moyenne, médiane, ou une étiquette).

### 1 à 4. Repérer les valeurs manquantes
- **Objectif** : compter et localiser les NaN.
- **Syntaxe** :
  - `df.isnull().sum()` → nombre de NaN par colonne
  - `df.isnull().sum().sum()` → total de NaN
  - `df.isnull().mean() * 100` → taux (%) par colonne
  - `df[df.isnull().any(axis=1)]` → les lignes contenant au moins un NaN

In [36]:
print("NaN par colonne :")
print(df.isnull().sum())

print("\nTotal de NaN :", df.isnull().sum().sum())

print("\nTaux de NaN (%) :")
print((df.isnull().mean() * 100).round(2))

print("\nLignes contenant des NaN :")
display(df[df.isnull().any(axis=1)])

NaN par colonne :
id_mesure             0
date_heure            0
id_capteur            0
batiment              0
temperature           6
humidite_relative     5
pression              5
consommation          5
etat                  4
niveau_temperature    0
dtype: int64

Total de NaN : 25

Taux de NaN (%) :
id_mesure             0.00
date_heure            0.00
id_capteur            0.00
batiment              0.00
temperature           0.99
humidite_relative     0.83
pression              0.83
consommation          0.83
etat                  0.66
niveau_temperature    0.00
dtype: float64

Lignes contenant des NaN :

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
14,M0056,2026-01-07 07:00:00,C008,B003,22.33,67.42,1014.41,101.20,NaN,Normale
30,M0073,2026-01-08 00:00:00,C001,B001,23.12,63.97,NaN,186.87,OK,Normale
91,M0473,2026-01-24 16:00:00,C005,B002,21.32,70.43,1021.20,194.76,NaN,Normale
128,M0300,2026-01-17 11:00:00,C012,B004,23.32,55.73,NaN,232.38,OK,Normale
139,M0345,2026-01-19 08:00:00,C009,B003,NaN,66.77,1015.33,216.31,OK,Normale
146,M0118,2026-01-09 21:00:00,C010,B004,30.32,NaN,1015.78,261.68,OK,Élevée
149,M0034,2026-01-06 09:00:00,C010,B004,28.91,NaN,1001.23,234.30,OK,Normale
163,M0019,2026-01-05 18:00:00,C007,B003,NaN,69.97,1014.14,181.07,OK,Normale
196,M0372,2026-01-20 11:00:00,C012,B004,29.33,56.91,1020.02,NaN,OK,Normale
215,M0204,2026-01-13 11:00:00,C012,B004,NaN,59.96,1007.98,294.02,OK,Normale
270,M0334,2026-01-18 21:00:00,C010,B004,29.63,67.70,1016.30,363.68,NaN,Normale
303,M0584,2026-01-29 07:00:00,C008,B003,23.78,64.66,NaN,153.81,OK,Normale
307,M0169,2026-01-12 00:00:00,C001,B001,21.86,51.83,NaN,195.72,OK,Normale
323,M0391,2026-01-21 06:00:00,C007,B003,21.82,NaN,1006.47,98.39,OK,Normale
459,M0143,2026-01-10 22:00:00,C011,B004,28.65,66.88,1001.41,NaN,OK,Normale
476,M0527,2026-01-26 22:00:00,C011,B004,26.16,NaN,1024.21,232.87,OK,Normale
490,M0227,2026-01-14 10:00:00,C011,B004,25.13,85.60,1011.20,NaN,ALERTE,Normale
491,M0449,2026-01-23 16:00:00,C005,B002,26.82,61.99,NaN,215.34,OK,Normale
511,M0506,2026-01-26 01:00:00,C002,B001,24.04,57.10,1014.04,NaN,OK,Normale
513,M0490,2026-01-25 09:00:00,C010,B004,NaN,52.97,1010.71,253.63,OK,Normale
526,M0015,2026-01-05 14:00:00,C003,B001,23.17,79.95,1006.07,NaN,OK,Normale
536,M0252,2026-01-15 11:00:00,C012,B004,27.01,NaN,1018.36,263.13,OK,Normale
548,M0572,2026-01-28 19:00:00,C008,B003,NaN,68.63,1018.58,252.48,OK,Normale
556,M0092,2026-01-08 19:00:00,C008,B003,NaN,79.81,1007.05,113.00,OK,Normale
572,M0190,2026-01-12 21:00:00,C010,B004,24.24,73.55,1018.12,299.91,NaN,Normale

### 5 à 7. Remplacer les valeurs manquantes
- **Objectif** : combler les NaN selon la colonne.
- **Syntaxe** : `df["col"].fillna(valeur)`
  - température & humidité → la **moyenne** (`.mean()`)
  - consommation → la **médiane** (`.median()`)
  - etat → l'étiquette **"INCONNU"**

In [ ]:
df["temperature"] = df["temperature"].fillna(df["temperature"].mean())
df["humidite_relative"] = df["humidite_relative"].fillna(df["humidite_relative"].mean())
df["consommation"] = df["consommation"].fillna(df["consommation"].median())
df["etat"] = df["etat"].fillna("INCONNU")

# Vérification
df.isnull().sum()