## Partie 1 – Series

Une **Series** est la structure de base de pandas : une colonne de données
à une seule dimension. Chaque valeur possède une étiquette appelée **index**.
On peut la voir comme une seule colonne d'un tableur, où l'index joue le rôle
des numéros de ligne.

### 1. Créer une Series contenant 4 températures

- **Objectif** : créer une Series à partir d'une liste de valeurs.
- **Syntaxe** : `pd.Series([valeur1, valeur2, ...])`

In [3]:
import pandas as pd

temperatures = pd.Series([22.5, 24.1, 19.8, 26.3])
temperatures

0    22.5
1    24.1
2    19.8
3    26.3
dtype: float64

### 2. Afficher l'index de la Series

- **Objectif** : voir les étiquettes attribuées à chaque valeur.
- **Syntaxe** : `ma_series.index`

In [6]:
temperatures.index

RangeIndex(start=0, stop=4, step=1)

### 3 & 4. Afficher la première et la dernière valeur

- **Objectif** : accéder à une valeur par sa **position**.
- **Syntaxe** : `ma_series.iloc[position]`
  - `iloc` = *integer location* = accès par position (0 = première).
  - La position `-1` désigne toujours le **dernier** élément.

In [7]:
print("Première valeur :", temperatures.iloc[0])
print("Dernière valeur :", temperatures.iloc[-1])

Première valeur : 22.5
Dernière valeur : 26.3

### 5. Créer une Series de températures indexée par les heures (12h à 15h)

Deux méthodes possibles :
- **Objectif** : associer à chaque température une étiquette (l'heure de mesure).
- **Syntaxe 1** (paramètre `index`) : `pd.Series(valeurs, index=liste_etiquettes)`
- **Syntaxe 2** (dictionnaire) : `pd.Series({etiquette: valeur, ...})`
  → les **clés** du dictionnaire deviennent automatiquement l'index.

In [8]:
# Façon 1 : avec le paramètre index
temp_heures_1 = pd.Series([22.5, 24.1, 19.8, 26.3], index=["12h", "13h", "14h", "15h"])
print("Façon 1 :")
print(temp_heures_1)

# Façon 2 : à partir d'un dictionnaire
temp_heures_2 = pd.Series({"12h": 22.5, "13h": 24.1, "14h": 19.8, "15h": 26.3})
print("\nFaçon 2 :")
print(temp_heures_2)

Façon 1 :
12h    22.5
13h    24.1
14h    19.8
15h    26.3
dtype: float64

Façon 2 :
12h    22.5
13h    24.1
14h    19.8
15h    26.3
dtype: float64

### 6. Afficher la première et la dernière valeur

- **Objectif** : réutiliser l'accès par position sur la Series indexée par heures.
- **Syntaxe** : `ma_series.iloc[0]` et `ma_series.iloc[-1]`
  (On pourrait aussi passer par l'étiquette : `ma_series["12h"]`, `ma_series["15h"]`.)

In [9]:
print("Première valeur :", temp_heures_1.iloc[0])
print("Dernière valeur :", temp_heures_1.iloc[-1])

Première valeur : 22.5
Dernière valeur : 26.3

## Partie 2 – DataFrame

Un **DataFrame** est un tableau à deux dimensions : plusieurs colonnes nommées
et des lignes indexées. C'est la structure centrale de pandas, équivalente à
une feuille de calcul.

### 1. Créer et afficher le DataFrame df_test

- **Objectif** : construire un DataFrame à partir d'un dictionnaire.
- **Syntaxe** : `pd.DataFrame(dictionnaire)`
  → chaque **clé** du dictionnaire devient un **nom de colonne**,
    et la **liste** associée devient le **contenu** de la colonne.

In [10]:
data = {
    "capteur": ["C001", "C002", "C003"],
    "temperature": [24.5, 25.1, 26.3],
    "humidite": [65, 67, 70]
}

df_test = pd.DataFrame(data)
df_test

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

### 2. Importer le dataset mesures_capteurs.csv dans le DataFrame df

- **Objectif** : charger un fichier CSV pour le transformer en DataFrame.
- **Syntaxe** : `pd.read_csv("chemin/vers/le/fichier.csv")`
  → `read_csv` lit un fichier de valeurs séparées par des virgules
    (CSV = *Comma-Separated Values*) et le convertit en DataFrame.

In [11]:
df = pd.read_csv("../data/mesures_capteurs.csv")
df

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
...,...,...,...,...,...,...,...,...,...
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

### 3. Afficher les dimensions de df

- **Objectif** : connaître le nombre de lignes et de colonnes.
- **Syntaxe** : `df.shape`
  → renvoie un couple `(nombre_de_lignes, nombre_de_colonnes)`.

In [12]:
df.shape

(605, 9)

## Partie 3 – Exploration

Avant d'analyser un jeu de données, on l'explore pour comprendre sa taille,
ses colonnes et le type de chaque information. C'est le premier réflexe de
tout data scientist face à un nouveau fichier.

### 1 & 2. Afficher les premières lignes

- **Objectif** : jeter un œil au début du tableau.
- **Syntaxe** : `df.head()` affiche les 5 premières lignes par défaut ;
  `df.head(n)` en affiche `n`.

In [13]:
print("5 premières lignes :")
display(df.head())

print("10 premières lignes :")
display(df.head(10))

5 premières lignes :

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

10 premières lignes :

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
5,M0595,2026-01-29 18:00:00,C007,B003,24.51,58.01,1013.34,146.10,OK
6,M0011,2026-01-05 10:00:00,C011,B004,29.23,70.43,1007.68,290.45,OK
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
8,M0444,2026-01-23 11:00:00,C012,B004,23.11,82.06,1021.96,293.36,OK
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK

### 3. Afficher les dernières lignes

- **Objectif** : regarder la fin du tableau.
- **Syntaxe** : `df.tail()` affiche les 5 dernières lignes (`tail` = « queue »).

### 4 & 5. Afficher le nombre de lignes et de colonnes

- **Objectif** : récupérer séparément le nombre de lignes puis de colonnes.
- **Syntaxe** : `df.shape` renvoie `(lignes, colonnes)`.
  On accède à chaque valeur par sa position : `df.shape[0]` (lignes),
  `df.shape[1]` (colonnes).

In [14]:
print("Nombre de lignes :", df.shape[0])
print("Nombre de colonnes :", df.shape[1])

Nombre de lignes : 605
Nombre de colonnes : 9

### 6. Afficher les noms des colonnes

- **Objectif** : lister les intitulés de colonnes.
- **Syntaxe** : `df.columns`

In [15]:
df.columns

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite', 'pression', 'consommation', 'etat'],
      dtype='str')

### 7. Afficher les informations générales

- **Objectif** : obtenir un résumé technique du tableau : nombre de lignes,
  nom et type de chaque colonne, et nombre de valeurs non-manquantes.
- **Syntaxe** : `df.info()`

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    str
 1   date_heure    605 non-null    str
 2   id_capteur    605 non-null    str
 3   batiment      605 non-null    str
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    str
dtypes: float64(4), str(5)
memory usage: 42.7 KB

### 8. Afficher les statistiques descriptives

- **Objectif** : obtenir d'un coup les statistiques des colonnes numériques
  (moyenne, min, max, écart-type, quartiles).
- **Syntaxe** : `df.describe()`

In [17]:
df.describe()

       temperature   humidite     pression  consommation
count   599.000000  600.00000   600.000000    600.000000
mean     24.878314   64.92620  1012.221900    208.675417
std       4.059576   10.76905    10.599042     72.243567
min     -18.500000   28.52000   850.000000     18.120000
25%      22.570000   58.17250  1006.790000    160.177500
50%      24.860000   65.37500  1012.855000    206.150000
75%      27.275000   71.61500  1017.827500    254.127500
max      58.700000  145.00000  1038.430000    875.000000

## Partie 4 – Sélection

Sélectionner, c'est extraire une partie du tableau : une colonne, plusieurs
colonnes, ou un sous-ensemble de lignes. Deux outils clés : `loc` (par étiquette)
et `iloc` (par position).

### 1. Sélectionner la colonne "temperature"
- **Objectif** : extraire une seule colonne (renvoie une Series).
- **Syntaxe** : `df["nom_colonne"]`

In [18]:
df["temperature"]

0      25.46
1      24.00
2      25.82
3      28.23
4      20.58
       ...
600    23.67
601    24.34
602    23.73
603    24.83
604    17.02
Name: temperature, Length: 605, dtype: float64

### 2. Sélectionner plusieurs colonnes
- **Objectif** : extraire plusieurs colonnes (renvoie un DataFrame).
- **Syntaxe** : `df[["col1", "col2", ...]]` → noter les **doubles crochets**.

In [19]:
df[["temperature", "humidite", "pression", "consommation"]]

     temperature  humidite  pression  consommation
0          25.46     58.06   1008.95        287.28
1          24.00     79.73    993.39        116.20
2          25.82     54.47   1010.32        288.50
3          28.23     69.39   1019.62        136.65
4          20.58     53.80   1016.58        182.62
..           ...       ...       ...           ...
600        23.67     60.28   1015.11        282.36
601        24.34     61.42   1019.43        357.43
602        23.73     63.49   1016.46        152.79
603        24.83     79.77   1017.05        170.97
604        17.02     52.04   1001.14         44.99

[605 rows x 4 columns]

### 3. Les 5 premières lignes avec loc
- **Objectif** : sélectionner des lignes par leur étiquette d'index.
- **Syntaxe** : `df.loc[debut:fin]` → avec `loc`, la borne de fin est **incluse**.

In [20]:
df.loc[0:4]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

### 4. Les 5 premières lignes et 4 premières colonnes avec iloc
- **Objectif** : sélectionner par **position** (numéros), lignes ET colonnes.
- **Syntaxe** : `df.iloc[lignes, colonnes]` → avec `iloc`, la borne de fin est **exclue**.

In [21]:
df.iloc[0:5, 0:4]

  id_mesure           date_heure id_capteur batiment
0     M0413  2026-01-22 04:00:00       C005     B002
1     M0290  2026-01-17 01:00:00       C002     B001
2     M0077  2026-01-08 04:00:00       C005     B002
3     M0079  2026-01-08 06:00:00       C007     B003
4     M0183  2026-01-12 14:00:00       C003     B001

## Partie 5 – Manipulation des colonnes

On peut créer de nouvelles colonnes, les catégoriser, les renommer ou les
supprimer. Ces opérations préparent les données pour l'analyse.

### 1. Ajouter la colonne "temperature_fahrenheit"
- **Objectif** : créer une colonne calculée à partir d'une autre.
- **Syntaxe** : `df["nouvelle"] = <calcul sur une colonne existante>`
- **Formule** : °F = °C × 9/5 + 32

In [22]:
df["temperature_fahrenheit"] = df["temperature"] * 9/5 + 32
df[["temperature", "temperature_fahrenheit"]].head()

   temperature  temperature_fahrenheit
0        25.46                  77.828
1        24.00                  75.200
2        25.82                  78.476
3        28.23                  82.814
4        20.58                  69.044

### 2. Ajouter la colonne "niveau_temperature"
- **Objectif** : catégoriser chaque ligne selon une condition.
- **Syntaxe** : `np.where(condition, valeur_si_vrai, valeur_si_faux)`
  → il faut importer numpy : `import numpy as np`.

In [23]:
import numpy as np

df["niveau_temperature"] = np.where(df["temperature"] > 30, "Élevée", "Normale")
df["niveau_temperature"].value_counts()

niveau_temperature
Normale    559
Élevée      46
Name: count, dtype: int64

### 3. Renommer "humidite" en "humidite_relative"
- **Objectif** : changer le nom d'une colonne.
- **Syntaxe** : `df.rename(columns={"ancien": "nouveau"})`
  → on réassigne le résultat à `df` pour que le changement soit conservé.

In [24]:
df = df.rename(columns={"humidite": "humidite_relative"})
df.columns

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite_relative', 'pression', 'consommation', 'etat',
       'temperature_fahrenheit', 'niveau_temperature'],
      dtype='str')

### 4. Supprimer la colonne "temperature_fahrenheit"
- **Objectif** : retirer une colonne devenue inutile.
- **Syntaxe** : `df.drop(columns=["nom_colonne"])`

In [25]:
df = df.drop(columns=["temperature_fahrenheit"])
df.columns

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite_relative', 'pression', 'consommation', 'etat',
       'niveau_temperature'],
      dtype='str')